### ISSUE TITLE
Crash entering a delivery

### ISSUE THREAD

**Issue by sde1000** [sde1000/quicktill#66]
At the Pembury: add item to delivery, choose stocktype, update number of items, then press enter to move down.

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/quicktill/till.py", line 65, in run
    curses.wrapper(start)
  File "/usr/lib/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "/usr/lib/python2.7/dist-packages/quicktill/till.py", line 42, in start
    event.eventloop()
  File "/usr/lib/python2.7/dist-packages/quicktill/event.py", line 36, in eventloop
    for i in rd: i.doread()
  File "/usr/lib/python2.7/dist-packages/quicktill/kbdrivers.py", line 45, in doread
    ui.handle_keyboard_input(i)
  File "/usr/lib/python2.7/dist-packages/quicktill/ui.py", line 98, in handle_keyboard_input
    basicwin._focus.hotkeypress(k)
  File "/usr/lib/python2.7/dist-packages/quicktill/ui.py", line 280, in hotkeypress
    self.parent.hotkeypress(k)
  File "/usr/lib/python2.7/dist-packages/quicktill/ui.py", line 280, in hotkeypress
    self.parent.hotkeypress(k)
  File "/usr/lib/python2.7/dist-packages/quicktill/ui.py", line 280, in hotkeypress
    self.parent.hotkeypress(k)
  File "/usr/lib/python2.7/dist-packages/quicktill/ui.py", line 280, in hotkeypress
    self.parent.hotkeypress(k)
  File "/usr/lib/python2.7/dist-packages/quicktill/ui.py", line 280, in hotkeypress
    self.parent.hotkeypress(k)
  File "/usr/lib/python2.7/dist-packages/quicktill/ui.py", line 280, in hotkeypress
    self.parent.hotkeypress(k)
  File "/usr/lib/python2.7/dist-packages/quicktill/ui.py", line 391, in hotkeypress
    basicwin._focus.keypress(k)
  File "/usr/lib/python2.7/dist-packages/quicktill/ui.py", line 636, in keypress
    if i[1] is None: i[0]()
  File "/usr/lib/python2.7/dist-packages/quicktill/stocktype.py", line 208, in finish_mode1
    self.dismiss()
  File "/usr/lib/python2.7/dist-packages/quicktill/ui.py", line 421, in dismiss
    self.parent.focus()
  File "/usr/lib/python2.7/dist-packages/quicktill/ui.py", line 1342, in focus
    self.draw()
  File "/usr/lib/python2.7/dist-packages/quicktill/ui.py", line 1361, in draw
    td.s.add(self.f)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1399, in add
    self._save_or_update_state(state)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1411, in _save_or_update_state
    self._save_or_update_impl(state)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1667, in _save_or_update_impl
    self._update_impl(state)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1660, in _update_impl
    self.identity_map.add(state)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/identity.py", line 119, in add
    % (key, ))
AssertionError: A conflicting state is already present in the identity map for key (<class 'quicktill.models.StockType'>, (2606,))
```

**Comment by sde1000** [comment]
This should be fixed by f41d501a454df5ef0cb75a6d72809fe9173a0479 - but wait and see!
